### PR TITLE
Add Debian 12 support

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by evgeni — APPROVED** [review]

**Comment by ekohl** [comment]
Fails because there is no bolt package available. Technically no Puppet package is even available and the distro doesn't package it. I'd be in favor of skipping bolt.

**Comment by ekohl** [comment]
Should we generalize the bolt exception here:
https://github.com/voxpupuli/puppet-redis/blob/364fb02b4d1f846eedb81639dafa1ef2a643772a/spec/spec_helper_acceptance.rb#L10-L14

**Comment by traylenator** [comment]
Obsoleted by #520

**Comment by evgeni** [comment]
520 merged

**Pull request closed without merging**
