### PR TITLE
release 7.0.0

### PR DESCRIPTION
**Pull request by bastelfreak**
should be rebased after https://github.com/voxpupuli/puppet-redis/pull/392 got merged

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
https://github.com/voxpupuli/puppet-redis/pull/398 should also make it in IMHO.

**Comment by bastelfreak** [comment]
@ekohl updated it

**Review by ekohl — CHANGES_REQUESTED** [review]
I labeled a bunch of unlabeled PRs that were merged. Please regenerate.

**Comment by bastelfreak** [comment]
@ekohl updated it again

**Review by ekohl — APPROVED** [review]

**Pull request merged**
