### PR TITLE
Add ability to configure a different template for the service

### PR DESCRIPTION
**Pull request by dandunckelman**
Relates to #260.  This adds the ability to use your own template file for the service.
- In my case, this will write the content I want for `/etc/systemd/system/redis-server.service`

So, I have this sort of role:

```
class ta_apps::redis (
  Hash   $config         = {},
  String $package_ensure = undef,
) {
  $service_template = 'ta_apps/redis_service.erb'

  package { 'software-properties-common':
    ensure => present,
  }

  class { '::redis':
    *                => $config,
    bind             => '0.0.0.0',
    daemonize        => false,
    databases        => 16,
    maxclients       => 4000,
    package_ensure   => $package_ensure,
    port             => 6379,
    protected_mode   => 'no',
    service_template => $service_template,
    syslog_enabled   => true,
    syslog_facility  => 'local0',
    timeout          => 0,
    unixsocket       => false,
    unixsocketperm   => false,
  }
}
```

Service template:

```
[Unit]
Description=Redis In-Memory Data Store
After=network.target

[Service]
User=redis
Group=redis
ExecStart=/usr/bin/redis-server
ExecStop=/usr/bin/redis-cli shutdown
Restart=always

[Install]
WantedBy=multi-user.target
```

Extra config coming from hiera:

```
ta_apps::redis::config:
  activerehashing: true
  aof_load_truncated: true
  aof_rewrite_incremental_fsync: true
  appendfsync: everysec
  appendonly: false
  auto_aof_rewrite_min_size: 64mb
  auto_aof_rewrite_percentage: 100
  hash_max_ziplist_entries: 512
  hash_max_ziplist_value: 64
  hll_sparse_max_bytes: 3000
  hz: 10
  latency_monitor_threshold: 0
  list_max_ziplist_entries: 512
  list_max_ziplist_value: 64
  no_appendfsync_on_rewrite: false
  rdbcompression: true
  save_db_to_disk: true
  save_db_to_disk_interval:
    900: 1
    300: 10
    60: 10000
  set_max_intset_entries: 512
  slowlog_log_slower_than: 10000
  slowlog_max_len: 1024
  stop_writes_on_bgsave_error: true
  tcp_backlog: 511
  tcp_keepalive: 60
  ulimit: 65536
  zset_max_ziplist_entries: 128
  zset_max_ziplist_value: 64
```

### CODE REVIEW

**Comment by dandunckelman** [comment]
Marked as WIP so I can add more detail.

**Comment by dandunckelman** [comment]
Removed WIP now that I've added detail from my working setup.

**Comment by dandunckelman** [comment]
This PR has morphed a bit since I'm using it in our production environment.

I had to incorporate the changes from https://github.com/arioch/puppet-redis/pull/239
- Thanks @petems

**Comment by ekohl** [comment]
I'm going to close this because of inactivity. We nowadays try to use the package provided service file and drop ins can be used as well. An updated PR would still be welcome.

**Pull request closed without merging**
