### PR TITLE
Add Debian 10 support

### PR DESCRIPTION
**Pull request by ekohl**
Closes GH-338

### CODE REVIEW

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet-redis/pull/345 should fix the bolt issue. Will rebase on it once merged.

**Comment by ghoneycutt** [comment]
@ekohl looks like it is failing on Debian 10 at https://github.com/voxpupuli/puppet-redis/blob/master/spec/spec_helper_acceptance.rb#L12

Seems the build is looking for mkdir in /usr/bin instead of /bin

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet-redis/pull/345 switches to using Bolt via the Puppet provided packages rather than Gems. Also updates from 0.5.1 to whatever is in the Puppet 5/Puppet 6 repos. That should fix it.

**Comment by ekohl** [comment]
Currently fails because there's no dotdeb repository for Buster: https://github.com/voxpupuli/puppet-redis/pull/346

**Pull request merged**
