### PR TITLE
Add Debian 11 support

### PR DESCRIPTION
**Pull request by ekohl**
Right now this is untested. I'll have to see what CI says.

### CODE REVIEW

**Comment by ekohl** [comment]
It looks like multi server doesn't work properly:
```
   Feb 22 10:39:09 debian11-64.example.com systemd[1]: redis-server-6379.service: Got notification message from PID 2027, but reception only permitted for main PID which is currently not known
```

Haven't looked into this further.

**Comment by root-expert** [comment]
If you need some insight https://github.com/voxpupuli/puppet-redis/pull/415. Although I haven't done much work either

**Comment by ekohl** [comment]
Ah, my bad. I somehow missed that one.

**Review by bastelfreak — APPROVED** [review]

**Comment by ekohl** [comment]
This is still a draft, no need to approve just yet.

**Comment by ekohl** [comment]
This should now be ready.

**Comment by root-expert** [comment]
Is it okay to change that for all OSes?
Maybe it should be configurable only for Debian 11?

**Comment by ekohl** [comment]
I thought about that, but we set `Type=notify` which means it can't daemonize. That was precisely the problem why it wouldn't start. So just like setting the supervisor to systemd (which must also be true with `Type=notify`), this must also always be true. And to me that CI passes with it says it's safe enough.

**Comment by ekohl** [comment]
Oh, and ideally speaking we would actually use the shipped `redis@.service` included in the Debian package since that actually contains more hardening.

**Comment by root-expert** [comment]
> I thought about that, but we set `Type=notify` which means it can't daemonize. That was precisely the problem why it wouldn't start. So just like setting the supervisor to systemd (which must also be true with `Type=notify`), this must also always be true. And to me that CI passes with it says it's safe enough.

You're right I had noted that on my PR as well

**Review by root-expert — APPROVED** [review]

**Pull request merged**
