### PR TITLE
Drop EL6 support

### PR DESCRIPTION
**Pull request by ekohl**
CentOS 6 is EOL and we can't test RHEL 6. That means there's no guarantee it continues to work.

### CODE REVIEW

**Review by alexjfisher — CHANGES_REQUESTED** [review]
Could we drop support and testing, but leave in the code for now?

That was the consensus at the last PMC meeting and @dhollinger has drafted a new policy document in https://github.com/voxpupuli/voxpupuli.github.io/pull/232

**Comment by ekohl** [comment]
I don't like having dead code. In fact, I'm thinking of completely dropping sysvinit code since after this, everything listed in metadata.json defaults to using systemd. This allows using the instance support built into systemd (and deployed by default on Debian), making the integration more native.

**Comment by ekohl** [comment]
In https://github.com/voxpupuli/puppet-redis/pull/382 I went to the next level. I'll keep both open for now, but I think that one has my preference.

**Review by kenyon — APPROVED** [review]

**Comment by bastelfreak** [comment]
closing this in favour of https://github.com/voxpupuli/puppet-redis/pull/382

**Pull request closed without merging**
