### PR TITLE
Require puppet-epel over stahnma-epel

### PR DESCRIPTION
**Pull request by dhoppe**

### CODE REVIEW

**Comment by dhoppe** [comment]
@ekohl I assume this pull request is ```backwards-incompatible```?

**Comment by ekohl** [comment]
Not sure what we decided. @alexjfisher @bastelfreak do you recall?

**Comment by bastelfreak** [comment]
@ekohl marked as backwards-incompatible. not because of the new namespace for epel, but for the changed lower epel version.

**Comment by ekohl** [comment]
Superseded by https://github.com/voxpupuli/puppet-redis/pull/358 so adding `skip-changelog` to keep it logical for the user.

**Pull request merged**
