### PR TITLE
Drop Puppet 5 support

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Review by bastelfreak — APPROVED** [review]

**Comment by ekohl** [comment]
Looks like it fails on Debian distros because puppet-bolt isn't available.

**Comment by kenyon** [comment]
> Looks like it fails on Debian distros because puppet-bolt isn't available.

Ah yes, you have to install `https://apt.puppet.com/puppet-release-$facts['os']['distro']['codename'].deb` to enable the puppet-tools component of the repo.

**Comment by ekohl** [comment]
Ah, kind of weird that there's a difference between deb and RPM repos for that.

**Comment by ehelms** [comment]
I noticed that this has a requires on `herculesteam/augeasproviders_core` which currently does not support Puppet 7:

https://github.com/hercules-team/augeasproviders_core/blob/master/metadata.json#L57

**Comment by bastelfreak** [comment]
I pinged Raphael for a new augesproviders_core release

**Comment by bastelfreak** [comment]
@ekohl can you rebase please?

**Comment by ekohl** [comment]
I've rebased this to a minimal version, but we haven't dropped Puppet 5 yet and given it's only metadata now (no actual code), I'd like to consider the alternative where we just add Puppet 7.

**Review by bastelfreak — APPROVED** [review]

**Comment by ekohl** [comment]
I've opened https://github.com/voxpupuli/puppet-redis/pull/400 to add Puppet 7 support.

**Comment by ekohl** [comment]
If https://github.com/voxpupuli/puppet-redis/pull/406 is merged, this should also get in.

**Comment by ekohl** [comment]
Rebased

**Review by bastelfreak — APPROVED** [review]

**Pull request merged**
